### ISSUE TITLE
do not stop timer when the phone gets locked.

### ISSUE THREAD

**Issue by fespinoza** [fespinoza/Todoro#4]
related to https://github.com/fespinoza/Todoro/commit/c12d025c05ac931af50cc8809cd32aa9ba1ffa02

## TODO:

- [x] restore the correct time when the app goes to foreground after being in background.
- [x] show local notification when the pomodoro time passes and the app is in the background.
- [x] execute the pomodoro completion code when the local notification is triggered.
- [x] show alert when trying to navigate back and a pomodo is running (cancel pomodoro if confirmed)
- [x] make sure there are no bugs regarding pomodoro presence.
- [x] make alert different for breaks and for pomodoros.

**Comment by fespinoza** [comment]
relevant: https://stackoverflow.com/questions/27585265/can-a-local-notification-trigger-code-in-ios8
